services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh -c "npm run build && npx prisma generate && npx prisma db push && npm run seed && npm run start"
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT}:4000"
    environment:
      PORT: ${BACKEND_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: /bin/sh -c "npm run build && npm run start"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      BACKEND_URL: ${BACKEND_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${FRONTEND_PORT}
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  postgres_data:
